/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.proyect.lms.view;

import com.proyect.lms.controller.CarreraController;
import com.proyect.lms.model.CarreraModel;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dany
 */
public class CarreraView extends javax.swing.JPanel {

    private CarreraController controller;
    private DefaultTableModel modeloTabla;

    public void setController(CarreraController controller) {
        this.controller = controller;
    }

    /**
     * Creates new form CarreraView
     */
    public CarreraView() {

    }

    public void initView() {
        initComponents();
        this.modeloTabla = new DefaultTableModel(new Object[0][2], new String[]{"ID", "Nombre"});
        this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        this.jTable1.getTableHeader().setReorderingAllowed(false);
        loadDataJTable();
        resetFields();
    }

    private void loadDataJTable() {
        List<CarreraModel> carreras = this.controller.obtenerTodasCarreras();
        this.modeloTabla.setRowCount(0);
        for (CarreraModel carrera : carreras) {
            this.modeloTabla.addRow(new Object[]{carrera.getCodigo(), carrera.getNombre()});
        }
        this.jTable1.setModel(this.modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreCarreraField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        clearBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        codigoCarreraField = new javax.swing.JTextField();
        editarCarreraBtn = new javax.swing.JButton();
        eliminarCarreraBtn = new javax.swing.JButton();
        crearCarreraBtn = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        jLabel1.setText("Carrera View");

        jLabel2.setText("Nombre de la carrera");

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        clearBtn.setText("Limpiar campos");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo carrera");

        codigoCarreraField.setEditable(false);

        editarCarreraBtn.setText("Editar");
        editarCarreraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCarreraBtnActionPerformed(evt);
            }
        });

        eliminarCarreraBtn.setText("Eliminar");
        eliminarCarreraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCarreraBtnActionPerformed(evt);
            }
        });

        crearCarreraBtn.setText("Crear");
        crearCarreraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCarreraBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCarreraField)
                            .addComponent(codigoCarreraField, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(editarCarreraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminarCarreraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(crearCarreraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoCarreraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreCarreraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crearCarreraBtn)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarCarreraBtn)
                            .addComponent(eliminarCarreraBtn))
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        resetFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
        System.out.println("fue escondido jijija");
    }//GEN-LAST:event_formComponentHidden

    private void editarCarreraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCarreraBtnActionPerformed
        String mensaje = this.controller.actualizarCarrera(this.codigoCarreraField.getText(), this.nombreCarreraField.getText());
        this.nombreCarreraField.setText("");
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        resetFields();
        loadDataJTable();
    }//GEN-LAST:event_editarCarreraBtnActionPerformed

    private void eliminarCarreraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCarreraBtnActionPerformed
        String mensaje = this.controller.eliminarCarrera(this.codigoCarreraField.getText());
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        resetFields();
        loadDataJTable();
    }//GEN-LAST:event_eliminarCarreraBtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        System.out.println("evt.getClickCount()"+evt.getClickCount());
        if (evt.getClickCount() == 1) {
            mostrarDatosEnCampos();
            this.crearCarreraBtn.setEnabled(false);
            this.editarCarreraBtn.setEnabled(true);
            this.eliminarCarreraBtn.setEnabled(true);
            this.clearBtn.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MousePressed

    private void crearCarreraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCarreraBtnActionPerformed
      String mensaje = this.controller.agregarCarrera(this.nombreCarreraField.getText());
        JOptionPane.showMessageDialog(this, mensaje, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        resetFields();
        loadDataJTable();
    }//GEN-LAST:event_crearCarreraBtnActionPerformed

    public void mostrarDatosEnCampos() {
        int filaSeleccionada = this.jTable1.getSelectedRow();
        try {
            if (filaSeleccionada != -1) {
                int codigo = (int) this.jTable1.getValueAt(filaSeleccionada, 0);
                String nombre = (String) this.jTable1.getValueAt(filaSeleccionada, 1);
                this.nombreCarreraField.setText(nombre);
                this.codigoCarreraField.setText(codigo + "");
            }
        } catch (Exception e) {
            System.out.println("error mostrar camop");
            resetFields();
        }

    }

    private void resetFields() {
        this.nombreCarreraField.setText("");
        this.codigoCarreraField.setText("");
       this.crearCarreraBtn.setEnabled(true);
        this.editarCarreraBtn.setEnabled(false);
        this.eliminarCarreraBtn.setEnabled(false);
        this.clearBtn.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField codigoCarreraField;
    private javax.swing.JButton crearCarreraBtn;
    private javax.swing.JButton editarCarreraBtn;
    private javax.swing.JButton eliminarCarreraBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nombreCarreraField;
    // End of variables declaration//GEN-END:variables
}
